services:
  postgres-db:
    container_name: quiz-the-office-db
    image: postgres:16-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=quiz_the_office
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=theoffice123
    networks:
      - quiz_the_office_net
    volumes:
      - quiz_the_office_pg_vol:/var/lib/postgresql/data

  # api:
  #   container_name: api
  #   env_file:
  #     - .env
  #   build:
  #     dockerfile: Dockerfile
  #   environment:
  #     - DB_DATABASE=${DB_DATABASE}
  #   restart: unless-stopped
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - postgres-db

  # mongo-db:
  #   image: mongo
  #   container_name: mongo-db
  #   ports:
  #     - "27017:27017"
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=mongoadmin
  #     - MONGO_INITDB_ROOT_PASSWORD=secret

volumes:
  quiz_the_office_pg_vol:

networks:
  quiz_the_office_net:
    name: quiz_the_office_net
