import type { Question, Character } from "../types/quiz"

export const QUIZ_QUESTIONS: Question[] = [
  {
    id: 1,
    question: "Qual é o nome completo do nosso querido chefe Michael?",
    options: ["Michael Gary Scott", "Michael George Scott", "Michael Grant Scott", "Michael Glenn Scott"],
    correct: 0,
    explanation: "Michael Gary Scott é nosso gerente regional favorito da Dunder Mifflin! 🎉",
    characterImage: "/placeholder.svg?height=120&width=120&text=😊+Michael",
    emoji: "👔",
    gif: "/placeholder.svg?height=200&width=300&text=Michael+Dancing",
    difficulty: "easy",
    season: 1,
  },
  {
    id: 2,
    question: "Em qual empresa nossos personagens trabalham?",
    options: [
      "Scranton Paper Company",
      "Dunder Mifflin Paper Company",
      "Pennsylvania Paper Co.",
      "Northeastern Paper Supply",
    ],
    correct: 1,
    explanation: "Dunder Mifflin é o lar dos nossos personagens favoritos! 🏢",
    characterImage: "/placeholder.svg?height=120&width=120&text=🏢+DM",
    emoji: "🏢",
    gif: "/placeholder.svg?height=200&width=300&text=Office+Building",
    difficulty: "easy",
    season: 1,
  },
  {
    id: 3,
    question: "Quem é o especialista em beterrabas do escritório?",
    options: ["Jim Halpert", "Stanley Hudson", "Dwight Schrute", "Creed Bratton"],
    correct: 2,
    explanation: "Dwight e suas beterrabas são inseparáveis! 🥬",
    characterImage: "/placeholder.svg?height=120&width=120&text=🥬+Dwight",
    emoji: "🥬",
    gif: "/placeholder.svg?height=200&width=300&text=Dwight+FALSE",
    difficulty: "medium",
    season: 2,
  },
  {
    id: 4,
    question: "Quem é a recepcionista mais querida de Scranton?",
    options: ["Karen Filippelli", "Angela Martin", "Kelly Kapoor", "Pam Beesly"],
    correct: 3,
    explanation: "Pam é o coração do escritório! ❤️",
    characterImage: "/placeholder.svg?height=120&width=120&text=❤️+Pam",
    emoji: "🎨",
    gif: "/placeholder.svg?height=200&width=300&text=Pam+Smiling",
    difficulty: "easy",
    season: 1,
  },
  {
    id: 5,
    question: "Qual é a frase mais icônica do Michael?",
    options: ["Bears. Beets. Battlestar Galactica.", "That's what she said!", "I am Beyoncé, always.", "Parkour!"],
    correct: 1,
    explanation: "Essa frase nunca sai de moda! 😂",
    characterImage: "/placeholder.svg?height=120&width=120&text=😂+Michael",
    emoji: "😂",
    gif: "/placeholder.svg?height=200&width=300&text=Michael+Laughing",
    difficulty: "easy",
    season: 1,
  },
  {
    id: 6,
    question: "Como Dwight carinhosamente chama o Jim?",
    options: ["Tuna", "Big Tuna", "Jimothy", "James"],
    correct: 1,
    explanation: "Big Tuna é um apelido que ficou para sempre! 🐟",
    characterImage: "/placeholder.svg?height=120&width=120&text=🐟+Jim",
    emoji: "🐟",
    gif: "/placeholder.svg?height=200&width=300&text=Jim+Pranking",
    difficulty: "medium",
    season: 3,
  },
  {
    id: 7,
    question: "Qual é a paixão culinária do Kevin?",
    options: ["Brownies", "M&Ms", "Cookies", "Donuts"],
    correct: 0,
    explanation: "Os brownies do Kevin são lendários! 🍫",
    characterImage: "/placeholder.svg?height=120&width=120&text=🍫+Kevin",
    emoji: "🍫",
    gif: "/placeholder.svg?height=200&width=300&text=Kevin+Eating",
    difficulty: "easy",
    season: 2,
  },
  {
    id: 8,
    question: "Quem cuida das contas da empresa?",
    options: ["Oscar Martinez", "Angela Martin", "Kevin Malone", "Stanley Hudson"],
    correct: 0,
    explanation: "Oscar é nosso contador mais confiável! 📊",
    characterImage: "/placeholder.svg?height=120&width=120&text=📊+Oscar",
    emoji: "📊",
    gif: "/placeholder.svg?height=200&width=300&text=Oscar+Working",
    difficulty: "medium",
    season: 1,
  },
]

export const CHARACTERS: Character[] = [
  {
    name: "Michael Scott",
    description:
      "Você é carismático, engraçado e sempre tenta fazer todos rirem! Às vezes exagera, mas tem um coração de ouro.",
    image: "/placeholder.svg?height=200&width=200&text=😊+Michael",
    minScore: 85,
    color: "bg-blue-50 border-blue-200 dark:bg-blue-900/20 dark:border-blue-700",
    quote: "I'm not superstitious, but I am a little stitious.",
    emoji: "👔",
  },
  {
    name: "Jim Halpert",
    description:
      "Você é inteligente, sarcástico e adora uma boa pegadinha! Sabe equilibrar trabalho e diversão perfeitamente.",
    image: "/placeholder.svg?height=200&width=200&text=😏+Jim",
    minScore: 70,
    color: "bg-green-50 border-green-200 dark:bg-green-900/20 dark:border-green-700",
    quote: "Bears. Beets. Battlestar Galactica.",
    emoji: "😏",
  },
  {
    name: "Dwight Schrute",
    description: "Você é dedicado, intenso e leva tudo muito a sério! Especialista em... bem, em muitas coisas!",
    image: "/placeholder.svg?height=200&width=200&text=🤓+Dwight",
    minScore: 55,
    color: "bg-yellow-50 border-yellow-200 dark:bg-yellow-900/20 dark:border-yellow-700",
    quote: "FACT: Bears eat beets. Bears. Beets. Battlestar Galactica.",
    emoji: "🤓",
  },
  {
    name: "Pam Beesly",
    description: "Você é criativa, gentil e observadora. É o tipo de pessoa que todos querem ter por perto!",
    image: "/placeholder.svg?height=200&width=200&text=🎨+Pam",
    minScore: 40,
    color: "bg-pink-50 border-pink-200 dark:bg-pink-900/20 dark:border-pink-700",
    quote: "I'm sorry, what was the question?",
    emoji: "🎨",
  },
  {
    name: "Kevin Malone",
    description: "Você é descontraído e gosta das coisas simples da vida. Às vezes confuso, mas sempre simpático!",
    image: "/placeholder.svg?height=200&width=200&text=😄+Kevin",
    minScore: 0,
    color: "bg-orange-50 border-orange-200 dark:bg-orange-900/20 dark:border-orange-700",
    quote: "Why waste time say lot word when few word do trick?",
    emoji: "😄",
  },
]
